//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectCinema.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REGISTER
    {
        public decimal USERID { get; set; }
        public string USERNAME { get; set; }
        public string PASSWORD { get; set; }
    }
}
